### ISSUE TITLE
Improve number inputs

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#1001]
See how bad it currently looks:
<img width="228" alt="Screenshot 2023-07-30 at 19 48 56" src="https://github.com/twentyhq/twenty/assets/6399865/c13a3ab5-61e6-4fcc-9203-f40007758bbb">

```[tasklist]
### Tasks
- [ ] Change Input number type to type=text
- [ ] Implement onKeyPress to only alow numbers: https://stackoverflow.com/questions/43687964/only-numbers-input-number-in-react
- [ ] Make sure it does not conflict with existing shortkeys: Cmd+K, Enter, Esc, Tab
```

**Comment by FelixMalfait** [comment]
Removing "Good first issue" because strategy/design is not clear

**Comment by charlesBochet** [comment]
I have added a strategy, putting back to good first issue!

**Comment by srikarsams** [comment]
Hey @charlesBochet, Nice to meet you. This is my first time here. I have couple of questions, and I apologise if it seems trivial.

- I just checked the code for this. If we change it to text input, operands are going to be `contains` and `does-not-contain` but it has to be `greater-than` and `less-than`. Isn't it? How to get around this?
- Also could you please elaborate more on the third task? 

Thanks!

**Comment by charlesBochet** [comment]
That's a fair point. you can use castToIntegerOrNull function to convert it to from src/utils
Regarding the first task, as you are going to add a onKeyPress eventHandler, it might cause issue with our existing shortkeys on the app (I don't think it will, but let's double check)
The expected behavior is that if you type something in the field an presse Enter or Esc, it should close the dropdown
Also, make sure that pressing Cmd+K (or Ctrl+K) is still opening the command bar menu

**Comment by srikarsams** [comment]
Hey @charlesBochet Thanks for the response. Do you still want me to use text input?  Using the text input will not display `Greater than` or `less than`. 
Sure, I'll make sure to check the keyboard hotkeys functionality. Thanks

**Comment by charlesBochet** [comment]
sorry about the confusion we should still use a type: 'number' in companies-filters.tsx but we should change the implementation of this type to actually display an HTML input type="text"

**Comment by srikarsams** [comment]
Ah okay! Got it. Thanks
