### ISSUE TITLE
Create Tasks Inbox

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#1005]
https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=5910-71591&mode=design&t=zFFDH9HSa9TJ9DFr-0

```[tasklist]
### Tasks
- [x] Refactor the TopBarComponent (might be wrongly called TableHeader) that is used on Table Views, Opportunity view to take a left component (ViewSelector on Opportunity and Tables) and a right components (OptionDropdowns)
- [x] Use this TopBar Component and inject Tabs as leftComponent (we already have a Tab UI component in storybook)
- [x] Display the list of un completed tasks grouped by day (do the grouping on the FE for now)
- [x] Do the list of completed tasks groupd by day
- [x] Improve dueDate display (right now we are using beautifulExact day but we should do something nicer, see figma)
- [x] Add the ability to filter by assignee
```

**Comment by charlesBochet** [comment]
This has been completed and integrated in v0.1.2
