### ISSUE TITLE
I can upload a photo on person show page

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#1022]
We recently added base64 images to the profiles that are initially seeded but it's a bit misleading because as of today you cannot upload a photo to a contact. 

We should be able to click on the avatar circle. That will open a window to upload an image from my local drive.
See how it's done in settings > profile for inspiration on picture upload.

<img width="187" alt="Screenshot 2023-07-31 at 16 31 46" src="https://github.com/twentyhq/twenty/assets/6399865/f6b418d5-e57e-4aa7-b79e-a3556c3b69de">

```[tasklist]
### Tasks
- [ ] Right now, we have one ShowPageSummaryCard component for companies and people. Their behavior is too different, we should create two separate components in @/companies and @/people
- [ ] In the People one, we can add a onclick function that triggers the upload
- [ ] We need to create a new resolver on people to upload a picture. You can take profile picture upload as an example
- [ ] Make sure to check ability-handler: you should not be able to update a person out of your workspace
- [ ] You will also need to introduce a new FileFolder
```

**Comment by charlesBochet** [comment]
@gitstart-twenty I have added some guidance on this one
