### ISSUE TITLE
Fix cascading deletion and foreign key

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#1041]
On opportunities board I saw an incorrect amount on the total of column.
After looking at the payload, it turns out that the backend returns cards for companies that have been deleted.
When we delete a company/person, it should delete the progressable entity.
Maybe there are other scenarios like this we should check (activities?)

Note this needs to be completed first:
https://github.com/twentyhq/twenty/issues/855
```[tasklist]
### Tasks
- [x] When I delete a company, Favorites, ActivityTargets and PipelineProgresses are deleted
- [x] When I delete a person: Favorites, ActityTargets and PipelineProgresses are deleted
- [x] When I delete a company, people that are attached to a company are detached
- [x] When I delete a company, users that are attached to the company are detached
```

**Comment by charlesBochet** [comment]
We can use cascade deletion to handle that

**Comment by charlesBochet** [comment]
Let's also add the missing foreign keys if there are

**Comment by gitstart-twenty** [comment]
Saw that you unassigned this earlier today, sorry about the delay. We were going to work on this today.

**Comment by charlesBochet** [comment]
No problem! I actually worked on this one this week-end, so I think it make sense that I complete it :)
