### ISSUE TITLE
Update phone/email links: underline, format international numbers

### ISSUE THREAD

**Issue by jenalla** [twentyhq/twenty#1055]
Need to improve the design and interaction for phone and email links by separating them from other links and modifying the behavior when clicking on the phone edit icon. Ticket linked to [#937](https://github.com/twentyhq/twenty/issues/937), [#938](https://github.com/twentyhq/twenty/issues/938) and [#883](https://github.com/twentyhq/twenty/issues/883) 

# Current Behavior: 

Currently, phone numbers appear with regular underlined formatting like other links on the platform and email addresses as an ordinary value. When clicking on a phone number to modify it, a standard input field opens for editing.

![Image](https://user-images.githubusercontent.com/102394218/257597839-5a90d358-5fc4-42ec-b6b4-69014a980f02.png)

# Desired Behavior: 

**1.	Design Enhancement:**
o	Phone and email links should be underlined, color = border/stronger , differentiating them from other links for better visual clarity
o	While hovering email links should also be underlined, color = text/primary 
o	While hovering phone links should also be underlined, color = text/primary and a pen should appear in the cell at the right

https://user-images.githubusercontent.com/102394218/257597980-9e449d52-151d-4d69-86ab-84a643fd55f9.mp4

**2.	Improved Interaction for Phone Edit:**
o	When click on the edit icon (pen) to modify a phone number, an overlay should open with additional options.
o	The overlay should allow users to change the country code associated with the phone number for improved flexibility.
o	Additionally, a button to copy the phone number should be available in the top right corner of the overlay for easier access.

https://user-images.githubusercontent.com/102394218/257598842-24fc58a3-a546-4a8c-86f7-76754c0b3c57.mp4

By implementing these changes, we aim to enhance the user experience, making it easier for users to interact with and modify phone and email links, and providing a clearer visual distinction between different types of links.

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=568-41746&mode=design&t=rPOh4WY5St9iTCHU-4

```[tasklist]
### Tasks
- [ ] Introduce a new ContactLink that will behave as described above (underline + hover), use this link in EditablePhoneCell, create and EditableEmailCell and use it there too
- [ ] Create a PhoneInput in @/ui/input that will use https://github.com/jackocnr/intl-tel-input
- [ ] Style the component according to design
- [ ] Ignore the copy phone number button for now
```

**Comment by jenalla** [comment]
Sure @mustajab-ikram! Thank you

**Comment by charlesBochet** [comment]
@mustajab-ikram I have added some guidance in the task list of the description :)
