### ISSUE TITLE
Add "All assignees" in Task team member dropdown (Good first issue)

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1077]
### Desired behavior

On the page with list of tasks, add an option called "All assignees" to enable seeing the tasks of the whole team (all the tasks):

![Image](https://github.com/twentyhq/twenty/assets/19412894/6c1ab0cd-9c34-47c0-9d72-c33e8ced915d)

```[tasklist]
### Tasks
- [ ] I would change FilterDropdownEntitySearchSelect to add this possibility. We need to add props to pass the icon and the label "All assignees"
- [ ] If these props are defined, display an aditional option to actually unselect all
- [ ] Then in SingleEntityFilterDropdownButton, we need to display the All assignees text (instead of 'Filter' which is actually never displayed)
```

**Comment by lazyfuhrer** [comment]
I'd like to work on this. assign me @Bonapara

**Comment by Weiko** [comment]
Thank you @lazyfuhrer! I just assigned it to you.

**Comment by charlesBochet** [comment]
@lazyfuhrer, I have added some guidance in the tasklist in the description

**Comment by charlesBochet** [comment]
@lazyfuhrer any update on this one? :)

**Comment by zvolcsey** [comment]
Hi! Can I work on this issue?

**Comment by Bonapara** [comment]
Hi @AyushAgrawal-A2 

1. Yes, "All assignees" should be shown among the filtered search results if the typed letter are matching e.g. when typing "All"
2. Not sure to understand properly your question. It should display the tasks from every member of the organization with the following label. Tell me if it's not clear!

![image](https://github.com/twentyhq/twenty/assets/19412894/134271cd-558c-42c1-b267-96e352925319)
