### ISSUE TITLE
Create Notes & tasks from CMD+K

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1080]
# Desired behavior

I want to create notes and tasks from the command bar:

![Image](https://github.com/twentyhq/twenty/assets/19412894/cd5135b5-149b-4314-a2bf-51be15d723e0)

# Bonus

It should take into account the context (If I'm on a show) and add the specific relations (If I'm on Stripe page, it should add Stripe as a relation)
```[tasklist]
### Tasks
- [ ] Add a Create Note and Create Task option in Command Menu (do not add short cut, the screenshot is not up-to-date)
- [ ] Create a recoil state in @/command-menu state: commandMenuCommand that would take an object of type Command { to: string, label: string, shortcuts?: string[], callback?: () => void
- [ ] Migrate commands (line 80) from commandMenu to this state. To do so, create a CommandMenuHook in src/sync-hooks that setRecoilState with these commands
- [ ] Now, we can start the feature :D create a addToCommandMenu function in useCommandMenu hook that can append a command to the existing state
- [ ] From AuthAutoRouter, on companies and people page, call addToCommandMenu with a callback that will call openCreateActivityDrawer with current entityId (we need to refactor openCreateActivity to take an id instead of an entity and fetch the entity)
- [ ] (Bonus) We also want to add the Create Task option in command menu if we are not on a company or people page, this means that we would like to create an activity with no entity assigned to it. Not sure it does not break everything, only do it if it seems doable without big refactoring
```

**Comment by sunilk4u** [comment]
Hi, I would like to get my hands on this one.

**Comment by charlesBochet** [comment]
Sounds good! Thank you!

**Comment by charlesBochet** [comment]
@sunilk4u I have added some guidance! Feel free to ping me here or on discord to discuss it!

**Comment by sunilk4u** [comment]
This is awesome. It is really helpful now. Thanks.

**Comment by sunilk4u** [comment]
@charlesBochet do you know where i can get enitity id (5th task) from ? because if i use useparams to get companyId or personId from url params, it comes out to be empty. These params are available in components respective to their route.

**Comment by charlesBochet** [comment]
Good point. To explain what I want to avoid adding a `useEffect` within the page:
My worry is to avoid creating unexpected re-renders once the page load. If addToCommandMenu is updating a state (`CommandMenuCommandsState`) that is read in the page, this will trigger a re-render. As `CommandMenu` is the only one reading this state, it should be fine and we can accept to have a `useEffect` in the page.

My second worry is that somebody will use this `useEffect` later for another usage and start triggering unwanted re-renders. By applying a "no useEffect" policy we protect ourself from this danger. (The only useEffect we authorize is the one in `AuthAutoRouter`)

So let's still keep trying to get the companyId in `AuthAutoRouter` (which is badly named as it starts doing more things). I think we should be able to get the company id by using something like: 
`    const match = matchPath({ path: '/companies/:id' }, location.pathname);`

**Comment by sunilk4u** [comment]
To refactor `openCreateActivity`, I could not find an graphql call for getting entitiy using the Id (I could find useGetCompany/useGetPeople). To make request on the basis of these two calls it will need a commentableType to make conditional request (which fails the point to refactor). Otherwise is there any other method to get enitity with id.

**Comment by charlesBochet** [comment]
LGTM in your PR :)

**Comment by charlesBochet** [comment]
These has been completed! Thank you @sunilk4u!
