### ISSUE TITLE
Improve display of numerous relations - Implement 'show more' Overlay

### ISSUE THREAD

**Issue by jenalla** [twentyhq/twenty#1086]
# Current Behavior:
Today, when there are too many relations, they are displayed without consideration of available space, leading to a cluttered appearance.
### Example issue on tasks:

https://user-images.githubusercontent.com/102394218/258555670-69f2c5c9-add6-45fc-ad88-cdc4c8b6374f.mp4

# Expected Behavior: 
The desired behavior is to apply a consistent display format for all multiple relations across the application.
### Proposed Solution:
1.	Limiting Width Div:
o	When displaying relations, constrain them within a maximum width div.
o	The div should not exceed the length of a single line.
2.	Displaying Maximum Elements:
o	Show the maximum number of relations that fit within the div.
3.	Adding 'Show More' Indicator:
o	If the div is full and there are additional non-displayed relations, add a '+n' indicator, representing the number of hidden relations.
4.	'Show More' Interaction:
o	Make the '+n' indicator clickable.
o	When clicked, open an overlay that expands to the div's width and accommodates the content to display all the hidden relations.

### Example desired behavior on tasks:

https://user-images.githubusercontent.com/102394218/258555611-b7dc316e-b028-4b35-b414-5bb7a3e21b7e.mp4

By implementing these changes, we aim to improve the display of numerous relations, ensuring a neat and organized presentation, and providing users with the option to access all relations via the 'Show More' overlay.

### Proposed implementation plan

```[tasklist]
### Tasks
- [ ] Introduce a @/ui/OverflowingChipsWithTooltip component that take children as an argument and applying a width: 100% to itself
- [ ] Add a useEffect to compute container size in js, compute estimated chip size based on text and icon
- [ ] Add a +n button with remaining items
- [ ] On click on the +n button, display a overflow div with the same width as it parent
- [ ] On click outside, close the overflow div
- [ ] Use this new component in Activity Right Panel, and on Task inbox
```

**Comment by jenalla** [comment]
@charlesBochet, can you help me with the technicality?

**Comment by mohitshende** [comment]
@jenalla Can I work on this?

**Comment by charlesBochet** [comment]
I will add direction in a few hours. We will also provide many new tickets that could be good candidates to work on!

**Comment by mohitshende** [comment]
Sure @charlesBochet. Actually I have implemented similar solution at my work, so I thought I can help here.

**Comment by charlesBochet** [comment]
@mohitshende I have added what I think is the right strategy as I don't see a proper way to do it in css. Does it make sense to you or do you have another approach?

**Comment by mohitshende** [comment]
@charlesBochet This makes sense. I can start working on it.

**Comment by charlesBochet** [comment]
Thank you!

**Comment by abhip167** [comment]
Starting to work on this. @mohitshende , if you are already done in some what capacity let me know.

**Comment by mohitshende** [comment]
> Starting to work on this. @mohitshende , if you are already done in some what capacity let me know.

Already started working on it, got busy with work. I will raise the PR in 1-2 days.

**Comment by charlesBochet** [comment]
@mohitshende any update on this one? :)

**Comment by mohitshende** [comment]
@charlesBochet I have completed all the tasks mentioned, the only issue that I am facing now is calculating the width of chip, because it is not possible to calculate the width of children without rendering them first.

**Comment by charlesBochet** [comment]
@mohitshende Let's try to calculate it based on text length + icon size. It won't be perfect but it should be good enough

**Comment by mohitshende** [comment]
@charlesBochet I have created the pull request for this issue, please review it.

**Comment by charlesBochet** [comment]
Thank you, we are having a look!

**Comment by FelixMalfait** [comment]
Hey @mohitshende I see you had done 90% of the work (thanks a lot for that!!! 🙏). Do you think you will ever pick it up or should we ask someone to take over the code you've started?

**Comment by mohitshende** [comment]
@FelixMalfait I tried solving some issues that were raised, but could not resolve them. Yes, you can ask someone to take over the code if they can provide a solution to it. I would be glad to assist them.

**Comment by charlesBochet** [comment]
I'm planning to work on this one this week :p I'll start from your code!

**Comment by Bonapara** [comment]
@charlesBochet should I unassign you from this one?

**Comment by charlesBochet** [comment]
No, I will keep it as we need to refactor this part and we are unclear on the strategy.

**Comment by codergirl2023** [comment]
@charlesBochet I see bunch of tasks can you assign me some task if left?

**Comment by FelixMalfait** [comment]
Got halfway there but spent way to much time on this. Closing to recreate an easier issue.
In case we ever come back to this, below is the code I had written which was kinda working but had a few edge cases.

```
diff --git a/packages/twenty-front/src/modules/activities/components/ActivityTargetChips.tsx b/packages/twenty-front/src/modules/activities/components/ActivityTargetChips.tsx
index c88d5f5e6..a1387480d 100644
--- a/packages/twenty-front/src/modules/activities/components/ActivityTargetChips.tsx
+++ b/packages/twenty-front/src/modules/activities/components/ActivityTargetChips.tsx
@@ -2,11 +2,13 @@ import styled from '@emotion/styled';

 import { ActivityTargetWithTargetRecord } from '@/activities/types/ActivityTargetObject';
 import { RecordChip } from '@/object-record/components/RecordChip';
+import { ChipsContainer } from '@/ui/display/chip/components/ChipsContainer';

 const StyledContainer = styled.div`
   display: flex;
   flex-wrap: wrap;
   gap: ${({ theme }) => theme.spacing(1)};
+  min-width: 200px;
 `;

 export const ActivityTargetChips = ({
@@ -16,15 +18,18 @@ export const ActivityTargetChips = ({
 }) => {
   return (
     <StyledContainer>
-      {activityTargetObjectRecords?.map((activityTargetObjectRecord) => (
-        <RecordChip
-          key={activityTargetObjectRecord.targetObject.id}
-          record={activityTargetObjectRecord.targetObject}
-          objectNameSingular={
-            activityTargetObjectRecord.targetObjectMetadataItem.nameSingular
-          }
-        />
-      ))}
+      <ChipsContainer>
+        {activityTargetObjectRecords?.map((activityTargetObjectRecord) => (
+          <RecordChip
+            key={activityTargetObjectRecord.targetObject.id}
+            record={activityTargetObjectRecord.targetObject}
+            objectNameSingular={
+              activityTargetObjectRecord.targetObjectMetadataItem.nameSingular
+            }
+            flexShrink="0"
+          />
+        ))}
+      </ChipsContainer>
     </StyledContainer>
   );
 };
diff --git a/packages/twenty-front/src/modules/object-record/components/RecordChip.tsx b/packages/twenty-front/src/modules/object-record/components/RecordChip.tsx
index 0da8ecf3b..69401be6d 100644
--- a/packages/twenty-front/src/modules/object-record/components/RecordChip.tsx
+++ b/packages/twenty-front/src/modules/object-record/components/RecordChip.tsx
@@ -8,6 +8,7 @@ import { EntityChip } from '@/ui/display/chip/components/EntityChip';
 export type RecordChipProps = {
   objectNameSingular: string;
   record: ObjectRecord;
+  flexShrink?: string;
   maxWidth?: number;
   className?: string;
 };
@@ -15,6 +16,7 @@ export type RecordChipProps = {
 export const RecordChip = ({
   objectNameSingular,
   record,
+  flexShrink,
   maxWidth,
   className,
 }: RecordChipProps) => {
@@ -35,6 +37,7 @@ export const RecordChip = ({
       avatarType={objectRecordIdentifier.avatarType}
       avatarUrl={objectRecordIdentifier.avatarUrl}
       linkToEntity={objectRecordIdentifier.linkToShowPage}
+      flexShrink={flexShrink}
       maxWidth={maxWidth}
       className={className}
     />
diff --git a/packages/twenty-front/src/modules/ui/display/chip/components/Chip.tsx b/packages/twenty-front/src/modules/ui/display/chip/components/Chip.tsx
index 9e6f5843d..2b28cf494 100644
--- a/packages/twenty-front/src/modules/ui/display/chip/components/Chip.tsx
+++ b/packages/twenty-front/src/modules/ui/display/chip/components/Chip.tsx
@@ -25,6 +25,7 @@ type ChipProps = {
   disabled?: boolean;
   clickable?: boolean;
   label: string;
+  flexShrink?: string;
   maxWidth?: number;
   variant?: ChipVariant;
   accent?: ChipAccent;
@@ -72,6 +73,9 @@ const StyledContainer = styled.div<Partial<ChipProps>>`
   height: ${({ size }) => (size === ChipSize.Large ? '16px' : '12px')};
   --chip-horizontal-padding: ${({ theme, variant }) =>
     variant === ChipVariant.Rounded ? theme.spacing(2) : theme.spacing(1)};
+
+  flex-shrink: ${({ flexShrink }) => (flexShrink ? flexShrink : 'inherit')};
+
   max-width: ${({ maxWidth }) =>
     maxWidth
       ? `calc( ${maxWidth}px - 2*var(--chip-horizontal-padding))`
@@ -116,7 +120,7 @@ const StyledContainer = styled.div<Partial<ChipProps>>`
   }
 `;

-const StyledLabel = styled.span`
+const StyledLabel = styled.span<Partial<ChipProps>>`
   overflow: hidden;
   text-overflow: ellipsis;
   white-space: nowrap;
@@ -131,6 +135,7 @@ export const Chip = ({
   leftComponent,
   rightComponent,
   accent = ChipAccent.TextPrimary,
+  flexShrink,
   maxWidth,
   className,
   onClick,
@@ -143,6 +148,7 @@ export const Chip = ({
     size={size}
     disabled={disabled}
     className={className}
+    flexShrink={flexShrink}
     maxWidth={maxWidth}
     onClick={onClick}
   >
diff --git a/packages/twenty-front/src/modules/ui/display/chip/components/ChipsContainer.tsx b/packages/twenty-front/src/modules/ui/display/chip/components/ChipsContainer.tsx
new file mode 100644
index 000000000..df896c382
--- /dev/null
+++ b/packages/twenty-front/src/modules/ui/display/chip/components/ChipsContainer.tsx
@@ -0,0 +1,73 @@
+import React, { useEffect, useRef, useState } from 'react';
+import styled from '@emotion/styled';
+import { useDebouncedCallback } from 'use-debounce';
+
+import { Chip } from '@/ui/display/chip/components/Chip';
+
+const StyledOverflowContainer = styled.div`
+  display: flex;
+  flex-wrap: nowrap;
+  overflow: hidden;
+  width: 100%;
+`;
+
+const StyledNodeWrapper = styled.span`
+  pointer-events: none;
+  position: fixed;
+  visibility: hidden;
+`;
+
+type OverflowIndicatorProps = {
+  children: React.ReactNode[];
+};
+
+export const ChipsContainer: React.FC<OverflowIndicatorProps> = ({
+  children,
+}) => {
+  const containerRef = useRef<HTMLDivElement>(null);
+  const [hiddenCount, setHiddenCount] = useState(0);
+
+  const updateHiddenCount = useDebouncedCallback(() => {
+    const container = containerRef.current;
+    if (!container) return;
+
+    let totalWidth = 0;
+    let newHiddenCount = 0;
+    Array.from(container.children).forEach((child) => {
+      totalWidth += child.getBoundingClientRect().width;
+      if (totalWidth > container.offsetWidth) {
+        newHiddenCount++;
+      }
+    });
+
+    setHiddenCount(newHiddenCount);
+  }, 100);
+
+  useEffect(() => {
+    const resizeObserver = new ResizeObserver(updateHiddenCount);
+    if (containerRef.current) {
+      resizeObserver.observe(containerRef.current);
+    }
+
+    updateHiddenCount();
+
+    return () => resizeObserver.disconnect();
+  }, [updateHiddenCount]);
+
+  return (
+    <StyledOverflowContainer ref={containerRef}>
+      {React.Children.map(children, (child, index) =>
+        index < children.length - hiddenCount ? (
+          child
+        ) : (
+          <StyledNodeWrapper>{child}</StyledNodeWrapper>
+        ),
+      )}
+      {hiddenCount > 0 && (
+        <div style={{ minWidth: '50px' }}>
+          <Chip label={`+ ${hiddenCount}`} />
+        </div>
+      )}
+    </StyledOverflowContainer>
+  );
+};
diff --git a/packages/twenty-front/src/modules/ui/display/chip/components/EntityChip.tsx b/packages/twenty-front/src/modules/ui/display/chip/components/EntityChip.tsx
index 9d64cba07..6f908e022 100644
--- a/packages/twenty-front/src/modules/ui/display/chip/components/EntityChip.tsx
+++ b/packages/twenty-front/src/modules/ui/display/chip/components/EntityChip.tsx
@@ -17,6 +17,7 @@ export type EntityChipProps = {
   variant?: EntityChipVariant;
   LeftIcon?: IconComponent;
   className?: string;
+  flexShrink?: string;
   maxWidth?: number;
 };

@@ -34,6 +35,7 @@ export const EntityChip = ({
   variant = EntityChipVariant.Regular,
   LeftIcon,
   className,
+  flexShrink,
   maxWidth,
 }: EntityChipProps) => {
   const navigate = useNavigate();
@@ -74,6 +76,7 @@ export const EntityChip = ({
       clickable={!!linkToEntity}
       onClick={handleLinkClick}
       className={className}
+      flexShrink={flexShrink}
       maxWidth={maxWidth}
     />
   );
diff --git a/packages/twenty-front/src/modules/ui/display/chip/components/__stories__/ChipsContainer.stories.tsx b/packages/twenty-front/src/modules/ui/display/chip/components/__stories__/ChipsContainer.stories.tsx
new file mode 100644
index 000000000..c5e5686d5
--- /dev/null
+++ b/packages/twenty-front/src/modules/ui/display/chip/components/__stories__/ChipsContainer.stories.tsx
@@ -0,0 +1,65 @@
+import styled from '@emotion/styled';
+import { Meta, StoryObj } from '@storybook/react';
+
+import { EntityChip } from '@/ui/display/chip/components/EntityChip';
+import { ComponentWithRouterDecorator } from '~/testing/decorators/ComponentWithRouterDecorator';
+
+import { ChipsContainer } from '../ChipsContainer';
+
+const StyledResizableDiv = styled.div`
+  overflow: auto;
+  resize: both;
+  width: 100%;
+`;
+
+const meta: Meta<typeof ChipsContainer> = {
+  title: 'UI/Display/Chip/ChipsContainer',
+  component: ChipsContainer,
+  decorators: [ComponentWithRouterDecorator],
+  args: {
+    children: [
+      {
+        name: 'Sh',
+      },
+      {
+        name: 'Long long long name',
+      },
+      {
+        name: 'Middle L',
+      },
+      {
+        name: 'Another one',
+      },
+      {
+        name: 'Entity 5',
+      },
+      {
+        name: 'Entity 6',
+      },
+      {
+        name: 'Entity 7',
+      },
+    ].map((child, index) => (
+      <EntityChip
+        flexShrink="0"
+        maxWidth={100}
+        key={index}
+        name={child.name}
+        entityId="1"
+        linkToEntity="/entity-link"
+        avatarType="squared"
+      />
+    )),
+  },
+};
+
+export default meta;
+type Story = StoryObj<typeof ChipsContainer>;
+
+export const Default: Story = {
+  render: (args) => (
+    <StyledResizableDiv>
+      <ChipsContainer>{args.children}</ChipsContainer>
+    </StyledResizableDiv>
+  ),
+};
```
