### ISSUE TITLE
Fix text color for dark mode

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#1096]
The text color of a few components are not well adapted to dark mode.

Check [figma](https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=0) for color values

Here are a few examples:

```[tasklist]
### Tasks
- [ ] Date picker
- [ ] Account deletion modal
- [ ] Task titles in tasks page
- [ ] Task relation view inside a person or a company
```

<img width="385" alt="Screenshot 2023-08-06 at 21 29 05" src="https://github.com/twentyhq/twenty/assets/1834158/829a23c0-71f2-46bd-93dd-1a35ba32318a">
<img width="427" alt="Screenshot 2023-08-06 at 21 29 18" src="https://github.com/twentyhq/twenty/assets/1834158/2e632297-e777-4b26-9ff9-b53e49b9146c">
<img width="731" alt="Screenshot 2023-08-06 at 21 29 31" src="https://github.com/twentyhq/twenty/assets/1834158/95f16123-f64e-4154-ae54-ca5fab671431">
<img width="1179" alt="Screenshot 2023-08-06 at 21 30 08" src="https://github.com/twentyhq/twenty/assets/1834158/81fc6a1a-7f77-4bab-8b24-28fa097fdf81">

**Comment by VARUN949** [comment]
i want to work on this
