### ISSUE TITLE
On Company Show, in team section, I can detach a person from a company

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#1107]
Todo when https://github.com/twentyhq/twenty/issues/1106 is complete

https://github.com/twentyhq/twenty/assets/19412894/ccf34831-5795-439a-bbfd-0c4f471b5f68

The scope of this ticket is to be able to detach a person from a company
```[tasklist]
### Tasks
- [ ] When I hover a PeopleCard, I see a 3 dots menu (using an IconButton)
- [ ] When I click on it, I see a dropdown Menu with a "Detach relation" option (see figma text/secondary)
- [ ] When I click on this option, the person is detached from the company
```
