### ISSUE TITLE
On Company Show, I can select an existing person and add it to the company

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#1108]
Todo once https://github.com/twentyhq/twenty/issues/1106 is complete

https://github.com/twentyhq/twenty/assets/19412894/ccf34831-5795-439a-bbfd-0c4f471b5f68

This ticket is about adding a plus button on top of team section on company show page
```[tasklist]
### Tasks
- [ ] Add a plus button using IconButton
- [ ] On Button Click, display a PersonPicker, make sure to wrap it in a component that would use useFloating to place the picker
- [ ] On Person selection, attach it to the company
```
