### ISSUE TITLE
On Company Show, I can create a person and add it to the company

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#1109]
Todo once https://github.com/twentyhq/twenty/issues/1108 is complete

https://github.com/twentyhq/twenty/assets/19412894/ccf34831-5795-439a-bbfd-0c4f471b5f68

This ticket is about creating a new person from the company show page
```[tasklist]
### Tasks
- [ ] In Team > Plus button > User Picker, add a "Create new" option (see CompanyPicker for example)
- [ ] On "Create New" click, display a DoubleTextInput with firstname and lastname fields
- [ ] On Enter, create a person and attach it to the company
```
