### ISSUE TITLE
Add a hover on Show Person Avatar

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1149]
# Desired behavior

To indicate it's possible to upload a picture on People Show, add a 4px "transparent lighter" border around the picture on hover.

```[tasklist]
### Tasks
- [x] Add a "onClick?: () => void" prop to Avatar.tsx
- [x] When this callback is passed as prop, trigger it on Avatar click
- [x] When this callback is passed, also add a 4px | 3px | 2px | 2px | 1px border at hover (color should  be transparent lighter)
- [x] Change PersonShow to use the onClick prop on Avatar
- [ ] Refactor the Avatar component to have a DefaultStory presenting all the options and a CatalogStory implementing them (see Chip.stories.tsx as an example)
```

**Comment by Bhavish5** [comment]
Hey, a small doubt could you explain what you mean by 4px transparent border?

**Comment by Bhavish5** [comment]
Hey @charlesBochet @Bonapara @Weiko all checks for my code have been passed can you review it? Thanks a lot for the support!

**Comment by charlesBochet** [comment]
@Weiko has left you comment on the PR @Bhavish5. Thanks a lot for your help

**Comment by PepeGonzale** [comment]
I would like to work on this tasks

**Comment by charlesBochet** [comment]
@Bhavish5 is already actively working on this one. Let's wait a bit before re-assigning it to somebody else :)

 @PepeGonzale, feel free to work on any other non taken good-first-issue

**Comment by charlesBochet** [comment]
@Bhavish5 are you still actively working on this issue?

**Comment by Bhavish5** [comment]
Sorry, for the delay this issue was a little complicated for me, hope to try some other issue. Thanks a lot for the help @charlesBochet.

**Comment by charlesBochet** [comment]
@PepeGonzale sure!

**Comment by FelixMalfait** [comment]
Thanks @PepeGonzale! Let us know if you have any question

**Comment by Bonapara** [comment]
@charlesBochet I closed this issue because it appears to have been merged, even though item 5 seems incomplete.
