### ISSUE TITLE
Update visible fields on person detail page

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1161]
On the people show, we should display the same properties as on the index page.

# Current behavior

There are some fields displayed on a table that are not displayed on the show page. For instance "Job title" on a person show page.

# Desired behavior
Add all the fields that are used in one of the index table views should be displayed on the show page. 

![Image](https://github.com/twentyhq/twenty/assets/19412894/985911e8-8614-424b-9878-a19ecf196491)

```[tasklist]
### Tasks
- [x] Add a FieldText to personShowFieldDefinition.tsx with fieldName: 'jobTitle' and the corresponding icon (IconBriefcase)
- [x] Add a FieldURL to personShowFieldDefinition.tsx with fieldName: 'linkedinUrl' and the corresponding icon (IconBrandLinkedin)
- [x] Add a FieldURL to personShowFieldDefinition.tsx with fieldName: 'xURL' and the corresponding icon (IconBrandX)
```

**Comment by kelvinyelyen** [comment]
Hey @Bonapara, I'm interested in working on this.

**Comment by Bonapara** [comment]
Thanks @kelvinyelyen!
