### ISSUE TITLE
Implement 404 page

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1163]
Back to content should go to the default view of companies

![Image](https://github.com/twentyhq/twenty/assets/19412894/8742128c-cec9-43e8-a49b-190e3c6bdb2a)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=9062-84249&mode=design&t=hSzJrpG9ok25Eoo2-4
```[tasklist]
### Tasks
- [ ] Create a NotFound page that display the content/styling above. Exceptionnaly, you don't have to use the theme to set the font-size (only!) as this will be too big and only used here
- [ ] Use CompanyMockTable to display the table below the background blur
- [ ] Add a CatchAll (*) route at the end of our routing in App.tsx that will redirect to this page
- [ ] On "Back to content", navigate to "/"
```
