### ISSUE TITLE
AADev, I have a SQL statement that I can run on production to create views for all existing workspaces

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#1196]
Views feature now assumes that all existing workspaces have at least 1 view defined for People table and Company table. This is not the case in production, make a sql statement that can be run on production to create these views. This should be done right before the deployment.
```[tasklist]
### Tasks
- [ ] Write a sql statement that loops over existing worksapces and insert into 3 views All People, All companies, Pipelines
- [ ] Remove viewFields with viewId undefined
- [ ] Run it right before production
```
