### ISSUE TITLE
Display a 404 on people/:id and company/:id when id does not exist

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#1352]
We already have implemented a 404 (NotFound) page that is triggered when the route does not match any existing pattern in `App.tsx`

We want to redirect to this page too when :id does not exist on PersonShow and CompanyShow pages
```[tasklist]
### Tasks
- [ ] introduce a route /not-found that will load NotFound page
- [ ] Make the "*" wildcard route in App.tsx redirect to /not-found page
- [ ] make redirect(NotFound) for PersonShow and CompanyShow routes (do that in sync-hooks/PageChangeEffect. We might want to extract these redirection guards into another file as PageChangeEffect is already quite long
```

**Comment by Weiko** [comment]
There is already a 404 component introduced in this PR https://github.com/twentyhq/twenty/pull/1230 by @sunilk4u that we can reuse

**Comment by PepeGonzale** [comment]
I would like to work on this!

**Comment by charlesBochet** [comment]
@PepeGonzale thank you! Please do!

**Comment by pranavp10** [comment]
@PepeGonzale are you working on this? i would like to take this up

**Comment by charlesBochet** [comment]
@pranavp10 as we have no update from Pepe, please go ahead!

**Comment by charlesBochet** [comment]
This ticket has actually been implemented, closing it!
