### ISSUE TITLE
Change design for icons in 'MainNavbar' and 'Pageheader'

### ISSUE THREAD

**Issue by jenalla** [twentyhq/twenty#1504]
# 1. NavItem Icon Styling:

Currently, the icons within NavItems in the MainNavbar have a 'md' stroke, which needs to be adjusted to 'sm'.

![Image](https://user-images.githubusercontent.com/102394218/266412072-b845a06c-e659-4e0a-b67d-2c3c18e41d1e.png)

# 2. NavbarCollapseButton Styling:

Similar to the NavItems, the NavbarCollapseButton's icon stroke should also be set to 'sm'. (The icons found both in the MainNavbar and in the PageHeader when the MainNavbar is in a collapsed state.)

 ### NavbarCollapseButton container:

Additionally, the NavbarCollapseButton container should be reduced to 24px from the current 32px.

![Image](https://user-images.githubusercontent.com/102394218/266413060-c9d51774-8c39-47a8-9ad1-24d06e873e66.png)

# 3. PageHeader IconButtons Styling:

IconButtons on the left side of the PageHeader should have their icon stroke set to 'sm' instead of 'md'. (visible on 'People' show and 'Company' show)
IconButtons container should be reduced to 24px. (from 32px)

### PageHeader Margin and Padding:

Add a margin-left of 4px to the left chevron icon in the PageHeader.

![Image](https://user-images.githubusercontent.com/102394218/266411500-71b57c77-d997-4b07-a133-c68b48d544db.png)

Remove the 8px padding from the div (in purple in the picture) that encompasses the page name and icons in the PageHeader.

![Image](https://user-images.githubusercontent.com/102394218/266411143-6679fc63-4d5a-4662-8267-b8f23e0e2659.png)

```[tasklist]
### Tasks
- [ ] NavItems in the MainNavbar: stroke to 'sm'
- [ ] NavbarCollapseButton's icon stroke set to 'sm'
- [ ] NavbarCollapseButton container reduced to 24px
- [ ] IconButtons left side PageHeader set their icon stroke to 'sm'
- [ ] The IconButtons left container in PageHeader should be reduced to 24px
- [ ] Add a margin-left of 4px to the left chevron icon in PageHeader
- [ ] Remove the 8px padding from the div (in purple in the picture)
```

**Comment by rbrtj** [comment]
Can i take it? :)

**Comment by pranavp10** [comment]
would like to work on this @jenalla

**Comment by FelixMalfait** [comment]
Thanks @ lot @pranavp10 great work!
