### ISSUE TITLE
Adjust the overlay style for changing the phone number's country

### ISSUE THREAD

**Issue by jenalla** [twentyhq/twenty#1505]
# Current design:

### Cell editable mode:
when you click to modify the cell, the flag has no hover

https://github.com/twentyhq/twenty/assets/102394218/fdb85275-29aa-4262-b2b4-c8225e81115b

### PickerMenu 

Currently, the picker component's design does not adhere to the Twenty style guidelines. It lacks the following key design elements:

- The appropriate background color.
- Correct font.
- Correct border and hover effects.
- A selected state.

![Image](https://user-images.githubusercontent.com/102394218/266417225-398ff2f4-6763-4340-97a5-007993fdc079.png)

# Expected design

### Cell editable mode:
add a hover transparent light

![Image](https://github.com/twentyhq/twenty/assets/102394218/8e8d780b-c326-4dd3-acdd-6af5c1141773)

### PickerMenu 

Adjust the design to align with the Twenty style. (Picture below)
if possible add flag, telephone index and a search.

![Image](https://user-images.githubusercontent.com/102394218/266418564-13772f01-bbfc-4252-aa65-4bcff6dc7f84.png)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=7184-122423&mode=design&t=aiEVp36gXiI1JZeu-4
```[tasklist]
### Tasks
- [ ] Right now, the phone input from libphonenumber-js is displaying a native dropdown. We should hide this existing dropdown (I'm not sure it's possible with the given API, we can use CSS if not)
- [ ] Introduce a new PhoneCountry Picker using MenuItemSelect and MenuItems
- [ ] Connect this picker to the existing input: we should update the country once selected and update the county once a format is detected
```

**Comment by jenalla** [comment]
@Nkiriobasi Sure! Thank you

**Comment by jenalla** [comment]
Hello @Nkiriobasi I added something to fix: the hover effect on the flag when you want modify a phone number.
