### ISSUE TITLE
Companies & People views new saving settings

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1580]
# Current behavior

Today, each change (listed below) brought to a view triggers the appearance of an "update view" button:

- Resizing a column
- Adding a column (field)
- Hiding a column (field)
- Filtering & sorting a view

This burdens the UX.

# Desired behavior

**filtering & sorting** persisting behavior should stay the same. Indeed, you may want to temporarily edit Filter & Sort at the user level, without your changes being immediately persisted for everyone: Keep Update View + Cancel behavior

- [ ]  **Resizing a column**, **Adding a column (field)**, and **Hiding a column (field)** should be persisted in the background without additional user action.

```[tasklist]
### Tasks
- [ ] Change Update View button + Cancel display condition to only take into account sorts and filters
- [ ] Persist change on viewFIelds (size, position, hide/show) automatically
- [ ] Change wording "Cancel" to "Reset"
```

**Comment by charlesBochet** [comment]
@thaisguigon What do you recommend here, I feel we will need a 3rd state:
- savedTableColumns (what is persisted in db)
- tableColumns (current state in front)
- initialTableColumns (what columns we had before starting making change)

Display the Reset button if tableColumns <> initialTableColumns or if there is change to persist on filters and sorts.
If we click on reset we re-save the initialTableColumns, resetFilters and resetSorts

**Comment by thaisguigon** [comment]
Are we going back on #1307 then? What is described in this issue was the initial behavior.
Also, should the "Reset" button reset columns or only filters and sorts @Bonapara ?

**Comment by Bonapara** [comment]
The reset button should only appear alongside the "update view" button. (It should never appear by its own.) 
The behavior stays the one of #1307 only for filtering & sorting.

For resizing a column, Adding a column (field), and Hiding a column (field) the changes should be persisted in background, without displaying the "Update view" button, nor the "cancel" button.
