### ISSUE TITLE
Add 'Esc' hotkey behavior on Filter and Sorts dropdown

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#1583]
**Current behavior**
On People Table, Companies Table, or on Opportunities Board, the Filter and Sort dropdown cannot be closed using 'esc' hotkey.

<img width="1512" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/9452a731-8c3a-4a12-b85b-efc1eeceb946">

**Describe the solution you'd like**
We would like 'esc' hotkey to be closing the dropdown and reseting its state.
The behavior should be exactly the same as the outsideClick behavior

```[tasklist]
### Tasks
- [ ] Add onClose callback to DropdownButton component
- [ ] In HotkeyEffect, register a new ScopedHotkey ('esc') to trigger both onClose and closeDropdown
- [ ] From MultipleFiltersDropdownButton, SingleEntityFilterDropdownButton, SortDropdownButton, use onClose to call resetState
```

**Comment by charlesBochet** [comment]
@lucasbordeau what do you think about the above strategy?
