### ISSUE TITLE
Implement the new "settingsTable" for active and disabled objects

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1762]
# About

We are introducing a new component called "SettingsTable" that can accommodate various types of rows (including the one for fields). It will be used for field settings and other use cases in the future. Please refer to the components in Figma for more details.

This component will be enhanced in the future.
![image](https://github.com/twentyhq/twenty/assets/19412894/7f7ea1f3-931a-4d8b-826a-9b269f24abc1)

![image](https://github.com/twentyhq/twenty/assets/19412894/2e11c825-b4f6-461b-9596-87f5e1bba76d)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11519-270312&mode=design&t=JTOVoeCGD6DTr2rv-4

# Behaviors
The table consist in 2 collapsable sections "Active" and "Disabled" (See definitions in #1756) 

### Collapsible sections
The "Disabled" section should be collapsed by default. Clicking on it should expand the section. Use a 300ms transition to animate the opening. Both the active and disabled sections should be collapsible.

### Navigation
- Clicking on an object in the "Active" section should navigate to the object detail page

https://github.com/twentyhq/twenty/assets/19412894/5b42a50e-6eeb-4411-a11e-bf5714f4461d

### Drag & drop
You can reorder "Active" objects by using the drag and drop option located on the left side of the row. By reordering these elements, their appearance in the workspace section of the app menu will also be rearranged. (see below)

![Screenshot 2023-09-28 at 19 05 35](https://github.com/twentyhq/twenty/assets/19412894/7d5311b9-ef7f-4bea-92e4-313efbec6428) should reorder:
![image](https://github.com/twentyhq/twenty/assets/19412894/bc2e32f1-088a-4f21-b724-0883df806128)

## Disabled

https://github.com/twentyhq/twenty/assets/19412894/8b67ffe3-e63d-497e-9801-10045c5eeb4f

### Disabled menu
Clicking on a row or the three-dot menu should open a menu with two options:
1. **Activate**: This option moves the object back to the "Active" state and displays it in the app.
2. **Erase**: For custom objects, this option deletes both the object and its associated data. For standard objects, it resets the object to its "default" state, erases all custom data and fields, and remains in the "Deactivated" state. The "Erase" option should not be displayed if the standard object is already in its default state.

![Screenshot 2023-09-28 at 19 14 23](https://github.com/twentyhq/twenty/assets/19412894/8f80d18a-7200-4c82-812d-767aac593837)

```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/1806
- [ ] https://github.com/twentyhq/twenty/issues/1799
- [ ] https://github.com/twentyhq/twenty/issues/1800
- [ ] https://github.com/twentyhq/twenty/issues/2005
- [ ] https://github.com/twentyhq/twenty/issues/1801
- [ ] https://github.com/twentyhq/twenty/issues/1802
- [ ] https://github.com/twentyhq/twenty/issues/2144
- [ ] https://github.com/twentyhq/twenty/issues/2147
- [ ] https://github.com/twentyhq/twenty/issues/1803
```

**Comment by charlesBochet** [comment]
@Bonapara Closing this issue!
