### ISSUE TITLE
[Timebox] Create DataTable dynamic page by URL

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#2041]
In this ticket we need to query our custom object with the part of the URL which contains the nameSingular (or namePlural, **to be defined**) of our custom object.

Out of scope: We should also **define** (maybe in another ticket) a strategy of how to show in the left nav bar the list of custom objects available. 
```[tasklist]
### Tasks
- [ ] Create route in App.tsx that point to a new page
- [ ] This page will load data table v2
- [ ] From url get the object name and pass it to data table v2
- [ ] [TImebox] Clean existing implementation in DataTablev2
```
