### ISSUE TITLE
🧩 New field types + add field preview

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2323]
# Scope & Context

The project aims to enable users to incorporate diverse field types into any Standard or Custom object.

Field types:
- Text
- Number
- Link
- True / False

New field types:
- Date
- Multi-select
- Select
- Pipeline steps
- Currency
- Phone
- Rating
- Image
- Relation

![CleanShot 2023-11-02 at 18 12 21@2x](https://github.com/twentyhq/twenty/assets/19412894/9c05bfba-4a05-4b3a-aad9-d9bf275859a3)

Later
- Lookup fields
```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/2343
- [ ] https://github.com/twentyhq/twenty/issues/2349
- [ ] https://github.com/twentyhq/twenty/issues/2325
- [ ] https://github.com/twentyhq/twenty/issues/2326
- [ ] https://github.com/twentyhq/twenty/issues/2328
- [ ] https://github.com/twentyhq/twenty/issues/2327
- [ ] https://github.com/twentyhq/twenty/issues/2331
- [ ] https://github.com/twentyhq/twenty/issues/2340
- [ ] https://github.com/twentyhq/twenty/issues/2477
- [ ] https://github.com/twentyhq/twenty/issues/2330
- [ ] https://github.com/twentyhq/twenty/issues/2329
- [ ] https://github.com/twentyhq/twenty/issues/2483
- [ ] https://github.com/twentyhq/twenty/issues/2334
- [ ] https://github.com/twentyhq/twenty/issues/2494
- [ ] https://github.com/twentyhq/twenty/issues/3534
- [ ] https://github.com/twentyhq/twenty/issues/2661
```

**Comment by charlesBochet** [comment]
@Bonapara we also need a phone type

**Comment by Bonapara** [comment]
@charlesBochet, I overlooked a crucial detail. In the future, some field types, such as the `Link field`, should support multiple values. For example, it could simultaneously store `google.com` and `g.co`.

**Comment by FelixMalfait** [comment]
Closing  this master issue to focus on sub-issues for now as the big milestone of shipping custom field types can be considered achieved (started 6+ months ago)
