### ISSUE TITLE
New field types : Select & Multi-select

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2329]
# Desired behavior

**Select** and **multi-select** functions are similar. The only distinction is that **select** allows only one option.

![CleanShot 2023-11-02 at 18 02 37@2x](https://github.com/twentyhq/twenty/assets/19412894/2c16e235-1cac-42e4-95d3-aa151c2021c7)

### 1. Right menu

The menu on the right should have two options: 
- Set as default
- Remove option

![CleanShot 2023-11-02 at 17 41 02@2x](https://github.com/twentyhq/twenty/assets/19412894/c594f906-e45a-4534-83e9-8f1460c0391a)

**Set as default** should add a "✔️" at the right end of the corresponding field

If there is a default option set, the first menu option should be **Remove as default** 

![CleanShot 2023-11-02 at 17 44 45@2x](https://github.com/twentyhq/twenty/assets/19412894/36cc13ce-0187-4bf9-8ed1-a35ae672c05d)

### 2. Color picker

The color picker should allow choosing the tag color:

https://github.com/twentyhq/twenty/assets/19412894/62090aef-4da9-41f9-8f0b-5b49a3211412

### 3. Drag & drop

Dragging and dropping options should reorder the tag above. When an "option" is selected to get reordered, the option background should change to **Transparent background light** 

![CleanShot 2023-11-02 at 17 52 31@2x](https://github.com/twentyhq/twenty/assets/19412894/859dd4a1-6efd-484d-ae69-e8d9a79df45b)

### 4. Cell and inline cell look

The cell and inline cell display should match the preview. There is no need for a "Pen" on the cells. Clicking on a cell should immediately enable value modification. Note that the design between the preview and the cells & inline cell should always match as the preview should actually be an **inline cell**

![CleanShot 2023-11-02 at 17 54 37@2x](https://github.com/twentyhq/twenty/assets/19412894/cda052ab-016f-4b22-8a91-1c769fe552bb)

Note the preview shows the options made below. But in its empty state, it should be:
- Use one green tag for Select: **Option**.
-  Use two tags for Multi-Select: **Option 1** (Green) and **Option 2** (Turquoise).

### 5. Add a new option

Clicking on **add option** should add a new row at the bottom of the other options.

- **tag color** The color of the option tag should be the next one on the list after the previous option. For example, if the first option is set to "Sky," the new tag should be "Blue." The first tag should be the first one in the list, which is "Green."
- **Placeholder** The placeholder should be _option name_

![CleanShot 2023-11-02 at 17 57 00@2x](https://github.com/twentyhq/twenty/assets/19412894/850d645f-5242-4aa9-8366-131988173e40)

# Cells & inline cells

https://github.com/twentyhq/twenty/assets/19412894/71dd5f37-4ddc-4fcc-b9fc-54a043119159

![CleanShot 2023-11-03 at 11 23 12@2x](https://github.com/twentyhq/twenty/assets/19412894/ebbdfe89-e403-4044-a5cd-b1150cd09fae)

Clicking on a selected value in a `select` picker should deselect it. It should be possible to have no selected value.

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=13736-50538&mode=design&t=nJ2HHxP3xoTZJB7T-11

# Figma

![image](https://github.com/twentyhq/twenty/assets/19412894/f01eb526-5135-499d-90f8-99928520b077)
https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=13884-59286&mode=design&t=avVSH5fvDzQPdLL9-11

![image](https://github.com/twentyhq/twenty/assets/19412894/810310a7-233f-4694-8939-4493df6f3a6e)
https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=13884-61065&mode=design&t=avVSH5fvDzQPdLL9-11

```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/2428
- [ ] https://github.com/twentyhq/twenty/issues/2432
- [ ] https://github.com/twentyhq/twenty/issues/2447
- [ ] https://github.com/twentyhq/twenty/issues/2587
- [ ] https://github.com/twentyhq/twenty/issues/2591
- [ ] https://github.com/twentyhq/twenty/issues/2433
- [ ] https://github.com/twentyhq/twenty/issues/2703
- [ ] https://github.com/twentyhq/twenty/issues/2704
- [ ] https://github.com/twentyhq/twenty/issues/2705
- [ ] New object field - Step 2 - Add "Multi-select" field type and preview
```

**Comment by FelixMalfait** [comment]
Closing as Select has been implemented. We can recreate a more narrow issue just for the scope of multi-select @Bonapara?
