### ISSUE TITLE
[Timebox] Adapt activities to new custom objects

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#2369]
## Scope & Context

The custom objects are now implemented but we still need to modify activity target so it can be used with custom objects.

## Current behavior

Activity targets are currently pointing on either companies or people.

## Expected behavior

We want activity targets to point on any custom object record. 

For this we would need to implement a solution that can reference a custom object and a record id.

Check : 
- ActivityTargetInlineCellEditMode
- useHandleCheckableActivityTargetChange
- useFilteredSearchEntityQuery (wait for new version in https://github.com/twentyhq/twenty/issues/2730)

```[tasklist]
### Tasks
- [ ] Implement activity target on object metadata id + record id
- [ ] Refacto field context / scope on activities
- [ ] Avoid creating empty activities (see existing issue + PR)
```

**Comment by charlesBochet** [comment]
This has been done, closing the issue
