### ISSUE TITLE
⛓️ [Master] Object relation display on show page

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3099]
# Current Behavior

We currently only display the `People` relation on the company show. However, we would like to introduce a generic behavior that allows us to display relations for any objects (custom or standard).

# Desired Behavior

Instead of displaying relations as inline fields, we want to introduce dedicated sections for each relation that a specific object has with other objects:

![CleanShot 2023-12-21 at 14 00 07](https://github.com/twentyhq/twenty/assets/19412894/2778d470-2355-407b-8f3c-470d9fdbcbf2)

### New relation record

Hover the section title to reveal a plus icon. This button allows you to create a new record for the related object:

https://github.com/twentyhq/twenty/assets/19412894/4afe45ee-6311-45e2-8ac9-23155136bcc9

The `Add new` button opens the text record identifier field (and the double input field for people and company)

### Temporary filtered index

**We'll limit object display to five records**. A temporary index will be created for accessing additional records. It will be accessible by clicking the `All (12)` section button:

https://github.com/twentyhq/twenty/assets/19412894/8a65f5e8-18b8-4a9a-825c-05686ce2bfcb

![CleanShot 2023-12-22 at 13 13 21](https://github.com/twentyhq/twenty/assets/19412894/ba9c5204-cd6d-4e3f-9e1b-ed0cdc01dfbc)

1. Replace the breadcrumb page name with a 'Back to _object text identifier_' button, redirecting to the show page. 
2. Display the object name, typically in the breadcrumb, in place of the view switcher. This won't be clickable. 
3. In the Navigation panel, no element will be active. Clicking the object name resets the index to the default view.
4. Removing all the filters does nothing. It keeps the user on the temporary view.

### Folded card

![CleanShot 2023-12-21 at 14 02 15](https://github.com/twentyhq/twenty/assets/19412894/9b12fb6d-4929-4a66-8dc9-64142eef543c)

1. Clicking on a chip goes to the corresponding record show
2. Clicking on the middle of the card expands the card
3. While hovering the card, a 3 dots menu appears on the right part:

https://github.com/twentyhq/twenty/assets/19412894/e06d20cc-c124-4b4a-9df5-2a7a65023ead

The options available allow for detaching a record (unlinking from this object) and permanent deletion. An alert popup for these actions will be implemented in the future.

### Unfolded card

Select the card center to expand it. Apply a transition for a smooth appearance, unlike Figma's instant display. Refer to the `Opportunities` `compact mode` for animation guidance.
Clicking another card closes the first one. (collapsible cards)

https://github.com/twentyhq/twenty/assets/19412894/60259e57-f843-4aff-81be-142ce5bf3f40

# Figma

**Please use the prototype!**

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=17315-103330&mode=design
```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/3123
- [ ] https://github.com/twentyhq/twenty/issues/3124
- [ ] https://github.com/twentyhq/twenty/issues/3125
- [ ] https://github.com/twentyhq/twenty/issues/3126
- [ ] https://github.com/twentyhq/twenty/issues/3128
- [ ] https://github.com/twentyhq/twenty/issues/3129
- [ ] https://github.com/twentyhq/twenty/issues/3127
- [ ] https://github.com/twentyhq/twenty/issues/3409
- [ ] https://github.com/twentyhq/twenty/issues/3610
- [ ] https://github.com/twentyhq/twenty/issues/4093
```

**Comment by Bonapara** [comment]
@thaisguigon I updated the "Temporary index" behaviors ☺️
