### ISSUE TITLE
☁️ Sign up to the cloud offering

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#375]
```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/405
- [ ] https://github.com/twentyhq/twenty/issues/395
- [ ] https://github.com/twentyhq/twenty/issues/396
- [ ] https://github.com/twentyhq/twenty/issues/397
- [ ] https://github.com/twentyhq/twenty/issues/403
- [ ] https://github.com/twentyhq/twenty/issues/406
- [ ] https://github.com/twentyhq/twenty/issues/398
- [ ] https://github.com/twentyhq/twenty/issues/407
- [ ] https://github.com/twentyhq/twenty/issues/400
- [ ] https://github.com/twentyhq/twenty/issues/401
- [ ] https://github.com/twentyhq/twenty/issues/402
```
