### ISSUE TITLE
Remote Objects: master issue

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3920]
This is the master issue to group all issues related to remote objects

```[tasklist]
### Stripe integration
- [ ] https://github.com/twentyhq/twenty/issues/5119#issue-2258262631
- [ ] https://github.com/twentyhq/twenty/issues/5060
- [ ] https://github.com/twentyhq/twenty/issues/5120
- [ ] https://github.com/twentyhq/twenty/issues/5121
- [ ] https://github.com/twentyhq/twenty/issues/5599
- [ ] https://github.com/twentyhq/twenty/issues/5600
- [ ] Check why the limit is 100
```

```[tasklist]
### Relations
- [ ] https://github.com/twentyhq/twenty/issues/5366
```

```[tasklist]
### Connection update
- [ ] https://github.com/twentyhq/twenty/issues/4765
- [ ] https://github.com/twentyhq/twenty/issues/4774
- [ ] https://github.com/twentyhq/twenty/issues/5083
- [ ] https://github.com/twentyhq/twenty/issues/4532
- [ ] https://github.com/twentyhq/twenty/issues/5062
- [ ] https://github.com/twentyhq/twenty/issues/5069
- [ ] Investigate bug coco: somethings / something
- [ ] https://github.com/twentyhq/twenty/issues/5610
- [ ] https://github.com/twentyhq/twenty/issues/5611
- [ ] https://github.com/twentyhq/twenty/issues/5612
```

```[tasklist]
### Misc V1
- [ ] https://github.com/twentyhq/twenty/issues/5058
- [ ] https://github.com/twentyhq/twenty/issues/5363
- [ ] https://github.com/twentyhq/twenty/issues/5362
- [x] Check the order of syncable tables remains the same
- [x] Issue with table names containing digits (marie)
- [ ] https://github.com/twentyhq/twenty/issues/5126
- [ ] https://github.com/twentyhq/twenty/issues/5364
- [ ] https://github.com/twentyhq/twenty/issues/5057
- [ ] Hide logs for Remote objects
- [ ] [Timebox] Test in prod
```

```[tasklist]
### Non-blocking
- [ ] https://github.com/twentyhq/twenty/issues/4535
- [ ] https://github.com/twentyhq/twenty/issues/5408
- [ ] Update user guide
- [ ] Block creation of a second connection to the same db (marie)
- [ ] Info banner dark mode version
```

## Legacy 

```[tasklist]
### Backend Tasks
- [ ] https://github.com/twentyhq/twenty/issues/3741
- [ ] https://github.com/twentyhq/twenty/issues/3742
- [ ] https://github.com/twentyhq/twenty/issues/3922
- [ ] https://github.com/twentyhq/twenty/issues/3923
- [ ] https://github.com/twentyhq/twenty/issues/3924
```

```[tasklist]
### Fronted Tasks
- [ ] https://github.com/twentyhq/twenty/issues/3926
- [ ] https://github.com/twentyhq/twenty/issues/4539
- [ ] https://github.com/twentyhq/twenty/issues/4543
- [ ] https://github.com/twentyhq/twenty/issues/4544
- [ ] https://github.com/twentyhq/twenty/issues/4552
```

### Temporary notes

Specific config per wrapper?
E.g. for postgres_fdw:
- Let's set `updatable = false` for every server for v1
- `keep_connections` by default set to `true` - let's leave it like that for v2but we'll probably need to followup later as this might cause scaling issues.

- createdAt/updatedAt position (defaultSort?)
- relationship with attachments, favorites, activityTarget...

```[tasklist]
### Tasks
```
