### ISSUE TITLE
📅 [Master] Settings/Accounts/Calendars page

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#4058]
https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=22605%3A135812&mode=dev
https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=22605%3A135758&mode=dev

```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/4059
- [ ] https://github.com/twentyhq/twenty/issues/4060
- [ ] https://github.com/twentyhq/twenty/issues/4061
- [ ] https://github.com/twentyhq/twenty/issues/4068
- [ ] https://github.com/twentyhq/twenty/issues/4292
- [ ] https://github.com/twentyhq/twenty/issues/4293
- [ ] https://github.com/twentyhq/twenty/issues/4184#issue-2153955422
```
