### ISSUE TITLE
🔑 Admin Panel

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4499]
## Context
We're taking a number of initiatives to make it easier for people to self-host.
One of them is the introduction of an admin panel for server admins. Most config should be manageabl from DB, not env.

## Sub-issues to create
- [ ] Rename `canImpersonate` to `canAccessAdminPanel` on users table
- [ ] Create a new /admin index page that is only accessible for people with `canAccessAdminPanel` permission. This page will only be accessible to a tiny portion of users so it would be good lazy load it (we already do that for setting pages)
- [ ] Create a page to manage config variables in admin panel
- [ ] Create a page to run data synchronization commands in admin panel
- [ ] Create a page dedicated to monitoring in admin panel
- [ ] Create a page dedicated to impersonation in admin panel
- [ ] Create a page dedicated to features flags in admin panel 
- [ ] Env var to disable admin panel entirely 

<img width="1021" alt="Screenshot 2024-03-15 at 12 29 28" src="https://github.com/twentyhq/twenty/assets/6399865/71aaebe5-9522-4dd4-b428-9e79ca632fd1">

**Comment by ehconitin** [comment]
This looks fun!
Could this issue be broken into small parts to work on?

**Comment by FelixMalfait** [comment]
@ehconitin sorry for the late reply!
I guess what you could do is:
- create `canAccessAdminPanel` on users table
- make sure the first user that is created as `canAccessAdminPanel` set to true (also set `canImpersonate` to true)
- add a section `Server` on the admin panel with 1 page (you could do the list of users with a button "impersonat", the list of featureFlags, list of keyValuePair, a basic monitoring page with info about redis queues, etc.)

That would be a great start! If we have that mechanism to create those private pages for system admins we would probably built upon it more often!

Forgot about the instructions I added in the initial post!
