### ISSUE TITLE
🔌 [Master] Remote Objects - Settings/Integrations/Database/Connection

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#4552]
https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=21730%3A65180&mode=design&t=CcFfmSAMGrVdyQty-1
```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/4556
- [ ] https://github.com/twentyhq/twenty/issues/4558
- [ ] https://github.com/twentyhq/twenty/issues/4560
- [ ] https://github.com/twentyhq/twenty/issues/4561
- [ ] Integrations/Database/Connection - About section - Add dropdown Edit option
- [ ] https://github.com/twentyhq/twenty/issues/4872
```

**Comment by FelixMalfait** [comment]
Closing master issue to cleanup
