### ISSUE TITLE
Refactor chrome-extension code

### ISSUE THREAD

**Issue by AdityaPimpalkar** [twentyhq/twenty#5263]
## Tasks

- [ ] Separate `content scripts` with their `utils` for scripts on special behaviour site (eg. LinkedIn, Gmail)
- [ ] Declare separate enums for `runtime` events and `tab` events with proper naming convention
- [x] Create a default button script
- [x] Refactor inject button script 
- [x] Replace iframe with sidepanel 
- [x] Refactor apollo client
- [ ] Separate individual query and mutation to separate file
- [ ] Remove `try..catch` on all db calls, handle exception on apollo level
- [ ] Cleanup unused images and files
