### ISSUE TITLE
✨ 0.1.3 UX Improvements

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#564]
```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/814
- [ ] https://github.com/twentyhq/twenty/issues/817
- [ ] https://github.com/twentyhq/twenty/issues/820
- [ ] https://github.com/twentyhq/twenty/issues/821
- [ ] https://github.com/twentyhq/twenty/issues/307
- [ ] https://github.com/twentyhq/twenty/issues/694
- [ ] https://github.com/twentyhq/twenty/issues/700
- [ ] https://github.com/twentyhq/twenty/issues/799
- [ ] https://github.com/twentyhq/twenty/issues/865
- [ ] https://github.com/twentyhq/twenty/issues/902
- [ ] https://github.com/twentyhq/twenty/issues/903
- [ ] https://github.com/twentyhq/twenty/issues/906
- [ ] https://github.com/twentyhq/twenty/issues/910
- [ ] https://github.com/twentyhq/twenty/issues/912
- [ ] https://github.com/twentyhq/twenty/issues/919
```
