### ISSUE TITLE
REST API problems

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6640]
**Scenario:**
1. Using any API client, e.g. Postman, send any request to REST API (e.g. GET http://localhost:3000/rest/companies)

**Actual:** REST API returns 500 error code with no message why request failed
![image](https://github.com/user-attachments/assets/33b6e3d6-c7c8-46fd-891d-251cce4d49d4)

**Expected:** REST API should return proper error code with clear message

```[tasklist]
### Tasks
- [x] Fix examples in the documentation
- [x] Basic fields like createdAt or deletedAt can't be overwritten
- [x] Change error messages to be more human-readable
```

**Comment by BOHEUS** [comment]
Okay, each comment will be one issue to make everything clear and I'll create a task list just in case.

**Comment by BOHEUS** [comment]
Most examples in the documentation are missing proper request body example, here are some examples with other related problems

There is a body with random ID in it, but when I send it, there's 500 error code (why there's an ID in first place and where does it come from?)
![image](https://github.com/user-attachments/assets/94f5e5d2-c5f8-4c07-96f3-c196f00038f7)

Here `secondaryLinks` are mentioned they're `Object` type, but what's the structure of them and what should they contain?
![image](https://github.com/user-attachments/assets/9c98c4d8-7947-486b-93a2-67ba3a688eb4)

There's depth but what does it mean for the end user? 
![image](https://github.com/user-attachments/assets/4c6ad99a-a0a5-4b69-b6c7-e594d2f66d59)

Why this **response** body says some fields are required?
![image](https://github.com/user-attachments/assets/83013531-8820-4e4a-81a6-1b0551136fb6)

Why there are fields like `createdAt` in request body? Shouldn't this be prohibited? (Somewhat related to #6581)
![image](https://github.com/user-attachments/assets/6879dcca-8a00-46dd-9e39-243f571f76be)

Also, schemas are missing proper example body
![image](https://github.com/user-attachments/assets/93c0e8f0-bb58-46ff-ba7c-7a153a5d0052)

**Comment by BOHEUS** [comment]
When creating a object with API, I'm able to override the `createdAt` and `deletedAt` fields which shouldn't be possible
![image](https://github.com/user-attachments/assets/618a9ce4-ee2e-4d04-9aeb-538aba30bc1c)

**Comment by charlesBochet** [comment]
@BOHEUS thanks a lot!

@martmull could you prioritize it next sprint. Also note that we will soon migrate the Rest API over TwentyORM (WorkspaceORM) instead of re-using the GraphQL API so do not over invest on the fixes :)

**Comment by BOHEUS** [comment]
@charlesBochet @martmull why I can't filter records using position? Why position is a **float** in first place?
```
{
  "statusCode": 400,
  "message": "Variable \"$filter\" got invalid value \"1\" at \"filter.and[0].position.eq\"; Float cannot represent non numeric value: \"1\"",
  "error": "Bad Request"
}
```
![image](https://github.com/user-attachments/assets/48c9e016-fa57-4e82-a948-d28b69f2e30d)

**Comment by martmull** [comment]
> Also, why the position has negative indexing?
@BOHEUS in `useComputeNewRowPosition.ts`, `computeNewPosition` can return negative new position when we move to first position if the current first record position has a position <= 0:
```
...
          if (moveToFirstPosition) {
            if (firstRecordPosition <= 0) {
              return firstRecordPosition - 1;
            } else {
              return firstRecordPosition / 2;
            }
          }
...
```
> Why position is a float in first place?
You can see is that function that position can also be a float as we divide by 2 is certain cases.
This allows to avoid updating all record positions when updating only one

**Comment by BOHEUS** [comment]
@martmull thanks for the answers!

**Comment by charlesBochet** [comment]
FYI we are almost ready to move the rest API direclty on top of the ORM and stopping having this underlying graphql call which is a nightmare to maintain :p
