### ISSUE TITLE
pg_graphql deprecation

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#6859]
```[tasklist]
### Tasks
- [x] Handle soft-delete (?)
- [x] Implement findOne
- [x] Implement findMany
- [x] Implement createOne/createMany
- [x] Implement updateOne/updateMany
- [x] Implement deleteOne/deleteMany
- [x] Implement findDuplicate
- [x] Implement destroyOne/destroyMany
- [ ] Implement nested totalCount
- [ ] Do not select all columns and use SelectedFields parsing
```
