### ISSUE TITLE
Add all necessary currencies

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7038]
Based on #7033 and other issues/PRs adding more currencies, instead of adding them one by one, it's better to add them all at once. This way, there won't be complaints about missing someone's currency or missing ability to add them by themselves in UI. 

```[tasklist]
### Tasks
- [ ] Research what currencies are available in the world
- [ ] Add currencies with correct code and symbols
- [ ] Add search for currencies when creating a new model like it's for Opportunities records ![image](https://github.com/user-attachments/assets/a34b95ed-0505-4650-a705-b65fcd69100c)
```

**Comment by harshit078** [comment]
Currently we are using around 20 currency and based on currency picker library and npm modules, we need to add around 10-15 more currency to support most used currency around the world which would bring the total count to be around 35

**Comment by BOHEUS** [comment]
Even if we all those 10-15 currencies, there are still more missing currencies according to ISO 4217 (https://en.wikipedia.org/wiki/ISO_4217#Active_codes_(list_one)), author of linked issue wanted to add a currency which isn't one of the most popular, so either:
- all available currencies in the world are added or
- Twenty should allow adding own currencies outside of base list

**Comment by BOHEUS** [comment]
@Bonapara what do you think, should all currencies be hardcoded or Twenty should allow adding them? If former, then I can implement this

**Comment by BOHEUS** [comment]
From fast check, it seems like there are missing icons for some currencies in icons-react package like Malagasy ariary or Ghanaian cedi, what should be done then? https://en.wikipedia.org/wiki/Currency_symbol

**Comment by Bonapara** [comment]
I think we can automate this. For icons we use Tabler-icons. Do you think we can fetch the ones available on tabler-icons and display `Coins` when the currency is not available?

<svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-coins"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M9 14c0 1.657 2.686 3 6 3s6 -1.343 6 -3s-2.686 -3 -6 -3s-6 1.343 -6 3z" /><path d="M9 14v4c0 1.656 2.686 3 6 3s6 -1.344 6 -3v-4" /><path d="M3 6c0 1.072 1.144 2.062 3 2.598s4.144 .536 6 0c1.856 -.536 3 -1.526 3 -2.598c0 -1.072 -1.144 -2.062 -3 -2.598s-4.144 -.536 -6 0c-1.856 .536 -3 1.526 -3 2.598z" /><path d="M3 6v10c0 .888 .772 1.45 2 2" /><path d="M3 11c0 .888 .772 1.45 2 2" /></svg>

**Comment by BOHEUS** [comment]
Sure, that won't be a problem

**Comment by BOHEUS** [comment]
@harshit078 could you add a search input in SettingsDataModelFieldCurrencyForm so users won't have to scroll whole, much bigger list to find currency they want? Also, @Bonapara, should search in Settings > Data model allow for searching currencies by their 3 letter code like it's done in Opportunities records (first screenshot)?
