### ISSUE TITLE
Create a ContextStore (Master ticket)

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#7335]
## Scope & Context

We want the ability to access the app context information in different components, to take actions consequently.
- ActionBar
- ContextMenu
- ViewBar
- CommandMenu
- Navigation

We want to have access to
- Current and previous pages
- Right drawer tabs
- Selected Records

```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/7336
- [ ] https://github.com/twentyhq/twenty/issues/7338
- [ ] https://github.com/twentyhq/twenty/issues/7339
- [ ] https://github.com/twentyhq/twenty/issues/7354
- [ ] Use the ContextStore for navigation
```
