### ISSUE TITLE
Use `<table>` or `role=table` for tables

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7854]
## Scope & Context

Right now, tables are made out of `<div>`
![image](https://github.com/user-attachments/assets/c4fe0b5f-8430-4beb-90fb-42c43f8e1e65)

## Technical inputs

Use `<table>`, `<thead>`, `<tbody>`, `<tr>`, `<td>` or respective `role=` attributes

CC: @Bonapara 

```[tasklist]
### Tasks
- [ ] Find all places where tables are made with `<div>`
- [ ] Decide with @CoreTeamTwenty on proper solution
- [ ] Implement changes in codebase
```

**Comment by dishafaujdar** [comment]
@BOHEUS  can I work on this ?

**Comment by Khaan25** [comment]
@Bonapara Shall I work on this accessibility issue?

**Comment by Bonapara** [comment]
We first need to agree on wether or not we should use `react-aria` -> https://github.com/twentyhq/twenty/issues/7803

**Comment by Bonapara** [comment]
We will not implement that in the short term
