### ISSUE TITLE
Use `<select>` for dropdowns

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7855]
## Scope & Context

Right now, all dropdowns and options are `<div>`s
![image](https://github.com/user-attachments/assets/de1cbe0d-be1b-4afd-bbde-82d85648cb03)
![image](https://github.com/user-attachments/assets/151ae180-7913-4500-b8bc-4d5648610af0)

## Technical inputs

All dropdowns should use `<select>` and options - `<option>`

```[tasklist]
### Tasks
- [ ] Find all places where dropdowns and options are made with `<div>`
- [ ] Decide with @CoreTeamTwenty on proper solution
- [ ] Implement changes in codebase
```

**Comment by ketanMehtaa** [comment]
please assign me , will work on it @BOHEUS .

**Comment by Bonapara** [comment]
We need to establish a global strategy, but it would make sense to implement it quickly if it includes the standard shortcuts (Arrow down, enter to select...). What do you think, @lucasbordeau?

**Comment by Bonapara** [comment]
Ok let's reopen it when we'll tackle Accessibility then
