### ISSUE TITLE
⚡Zapier Master Issue

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#8149]
```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/8130
- [ ] https://github.com/twentyhq/twenty/issues/6071
- [ ] https://github.com/twentyhq/private-issues/issues/124
```
