### ISSUE TITLE
Opportunities menu: add and edit stages

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#818]
# Behavior
Step edition is the same that the one we already implemented on column renaming

https://github.com/twentyhq/twenty/assets/19412894/b28ec0db-baec-4a72-8733-8f3aa8f66269

# Figma 

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=5910-77816&mode=design&t=M5AEwaW9oO64UPwK-4

```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/1395
- [ ] https://github.com/twentyhq/twenty/issues/1396
- [ ] List pipeline stages in Options dropdown and implement pipeline stage visibility
- [ ] Add pipeline stage reordering in Options dropdown
```

**Comment by FelixMalfait** [comment]
Setting this as back+front because ordering/renaming already exists but the visible/hidden does not so it will require a small modification to the backend to do this

**Comment by thaisguigon** [comment]
As discussed with @charlesBochet : 
For now we're implementing a "Delete view" option in the pipeline stage's label dropdown.
We might want to link pipeline stage visibility to Views, so implementing Views on Opportunities board first might be required.

**Comment by AdityaPimpalkar** [comment]
I think we have most of the parts in current codebase to implement this? 🤔 
If there isn't anything missing, can I take this up? 😄

**Comment by charlesBochet** [comment]
Sure @AdityaPimpalkar thank you!

**Comment by Bonapara** [comment]
Closing, as we will handle this in the Settings instead of in the app.
