### ISSUE TITLE
Update docs with solutions from #help Discord

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#8296]
When people have problems with Twenty, they either create an issue/discussion here or a ticket on Discord server, even though everything is searchable using standard web search engine like DuckDuckGo (tickets can be found outside of the server as there's Answer Overflow bot which is responsible for creating pages per ticket), the first step for most people when they have problem is checking documentation which is missing solutions for some problems.

```[tasklist]
### Tasks
- [ ] Check all tickets on Discord server
- [ ] Find problems with missing solutions in docs
- [ ] Update docs with problems and solutions like it's done in Troubleshooting section in Local setup (maybe create a new page only for Troubleshooting?)
```

**Comment by Bonapara** [comment]
@BOHEUS, would you like to create a V1 of this? I think developing a Self-Hosting Troubleshooting page could be a good idea!

**Comment by BOHEUS** [comment]
Sure

**Comment by BOHEUS** [comment]
@Bonapara where this page should be located? In `twenty-website/src/content/developers` or in `twenty-website/src/content/developers/self-hosting`?
