### ISSUE TITLE
Update 1-click script

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#8322]
Update 1-click script to make it really 1-click or 1 command

```[tasklist]
### Tasks
- [ ] Write a bash script for automatic setup
- [ ] Include in script all manual steps
- [ ] Test script if it's working
```

### Remember about downloading files from releases, not main branch as docs are updated after release

**Comment by FelixMalfait** [comment]
I updated the script so that it downloads the file from the versioned branch not the main branch already. 
What else would do you think we should change?

**Comment by BOHEUS** [comment]
I was thinking about making a bash script which automates all the steps, all what user would have to do is provide values for variables like tag version, database password and such, I can create a POC if that's not a problem

**Comment by FelixMalfait** [comment]
We already have that though?!
https://twenty.com/developers/section/self-hosting/docker-compose

`bash <(curl -sL https://git.new/20)`

**Comment by BOHEUS** [comment]
You're completely right, I'm sorry for misunderstanding, I was reading docs and didn't check the script itself :bow: 
Since script automates setting variables, can "Manual steps" section be deleted from docs or should it stay just in case someone may need changing settings?

**Comment by FelixMalfait** [comment]
No problem at all! You do so many great reports, you can't have 100% accuracy 😂
I think it's good to keep detailed manual steps as expert users sometimes prefer to have more control and run all the steps manually themselves
