### ISSUE TITLE
🗂️ Views

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#850]
```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/817
- [ ] https://github.com/twentyhq/twenty/issues/813
- [ ] https://github.com/twentyhq/twenty/issues/915
- [ ] https://github.com/twentyhq/twenty/issues/849
- [ ] https://github.com/twentyhq/twenty/issues/851
- [ ] https://github.com/twentyhq/twenty/issues/889
- [ ] https://github.com/twentyhq/twenty/issues/879
- [ ] https://github.com/twentyhq/twenty/issues/1147
- [ ] https://github.com/twentyhq/twenty/issues/914
- [ ] https://github.com/twentyhq/twenty/issues/927
- [ ] https://github.com/twentyhq/twenty/issues/1524
```
