### ISSUE TITLE
🛠️ Display, filter and sort via nested objects

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#853]
```[tasklist]
### Tasks
- [ ] I can filter with company properties on opportunities
- [ ] I can filter with company properties on people list
- [ ] I can display company properties in people list
- [ ] I can sort via company properties in people list
```

**Comment by Bonapara** [comment]
Closing as not planned in the short term

**Comment by breakingflower** [comment]
Hi
To be able to filter on attributes of other objects in the GUI is an important feature for a CRM. 
I asked deepwiki and he gives the answer that it's possible with GraphQL but not in the GUI. 

Is this in scope in near term, or am i missing something?

Example 
- I want to filter people on attribute company.location.zip_code = 5000EK 
- I want to filter people on attribute customObject.time between '2025-01-03' and '2025-02-05'
