### ISSUE TITLE
📂 Favorites Folders follow-up

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#8545]
We made great progress with the Favorites Folders feature. Here are a few points to address:

```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/8546
- [ ] https://github.com/twentyhq/twenty/issues/8549
- [ ] Try build Favorite Picker without recoilState (only useState) -- deprecated
- [x] Fix Scroll / Drag behavior using ScrollWraper
- [x] Make a pass with Charles on how to improve the existing code (duplicated code)
- [x] (post 0.33) remove feature flags
- [ ] https://github.com/twentyhq/twenty/issues/8569
- [ ] add RemoteNavigationDrawerSection.stories.tsx back when seed data is updated to include data with isRemote=true
- [ ] https://github.com/twentyhq/twenty/issues/9299
- [ ] https://github.com/twentyhq/twenty/issues/9213
```

**Comment by FelixMalfait** [comment]
@ehconitin closing the master issue! Could you please create a new issue if there are thing that are still relevant? Thanks a lot
