### ISSUE TITLE
Negative number of employees

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#882]
Company can have negative number of employees - solution: assure that number of employees can't be less than 1 and it has to be a whole number, you can't divide a human

Scenario:
1. Add new record in Companies or modify existing record and insert zero or negative number or fraction of number

Actual: Company can have half of employee or -2 employees
Expected: Company should have at least 1 whole employee, inserting fraction or number less than 1 should result in error/clear message to user
```[tasklist]
### Tasks
- [ ] Create a cast-as-positive-integer-or-null guard like the cast-as-integer-or-null guard
- [ ] Add a metadata "isPositive": true in CompanyViewField and pass it in the GenericEditableNumberCell
- [ ] Use the guard there
```

**Comment by FelixMalfait** [comment]
One way to solve this would be to pass additional props for inplace input and set type="number", min="1".

But that would add arrows like in the image below. @Bonapara is that something we want or not?

<img width="196" alt="Screenshot 2023-07-30 at 08 19 59" src="https://github.com/twentyhq/twenty/assets/6399865/80e53a35-ff45-4925-82a7-ae777b4b9232">

**Comment by Bonapara** [comment]
I think we should put a simple "validation" on the input, and reset to the previous value if the value is negative. (The previous value can be nothing)

**Comment by charlesBochet** [comment]
We should use a cast-as-positive-integer-or-null (see task list in the ticket description)

**Comment by srikarsams** [comment]
Hey @charlesBochet , can I work on this?

**Comment by FelixMalfait** [comment]
@srikarsams sure thanks a lot! Make sure to follow the task list

<img width="602" alt="Screenshot 2023-08-08 at 21 46 00" src="https://github.com/twentyhq/twenty/assets/6399865/fcd8e949-cb2c-496b-b28d-8c68fcb5baf7">

**Comment by srikarsams** [comment]
Addressed this issue here #1130
