### ISSUE TITLE
Add validation on company URL

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#884]
Company's URL can be only one letter or number

Scenario:
1. Add new record in Companies or modify existing one and insert one character in company's URL

Actual: Record is properly saved
Expected: If record doesn't match the regex, then the new value should not be persisted in database, and we should put back the previous value. See NumberEditableCell for example
```[tasklist]
### Tasks
- [ ] Create a is-url guard (similar to can-be-cast-as-integer-or-null) with test
- [ ] Use it in URLEditableCell (see NumberEditableCell for example)
- [ ] Add unit test (see can-be-cast-as-integer-or-null) for guidance
```

**Comment by srikarsams** [comment]
Hey @charlesBochet, domain name should have atleast one number or letter. For eg: `https://g.com`. Isn't it?

**Comment by charlesBochet** [comment]
@srikarsams Let's use a regex for that: https://stackoverflow.com/questions/10306690/what-is-a-regular-expression-which-will-match-a-valid-domain-name-without-a-subd

**Comment by srikarsams** [comment]
Hey @charlesBochet , thanks for the help. Can I work on this?

**Comment by charlesBochet** [comment]
Sure!
