### ISSUE TITLE
Onboarding should happen on a single route

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#950]
# Current behavior

Today, when created a workspace, I will successfully be redirected to:
https://app.twenty.com/sign-up
https://app.twenty.com/create/workspace
https://app.twenty.com/create/profile

# Desired behavior

Everything should only happen on two routes:
1) /Sign-up
2) /onboarding

I should be able to navigate (especially go back) between steps.

Later there will be some animations between steps. Let's anticipate this, even if we will do it later.

```[tasklist]
### Tasks
- [ ] Refactore create/workspace and create/profile into one onboarding page
- [ ] Do not force redirect between workspace creation and profile creation
- [ ] Make sure previous/next is working between the page
- [ ] Make sure to load the right step on page load depending on the onboarding state (but only on load, then let the user go back and forth if he wants)
- [ ] Make sure this works with all workflows (invite, sign up credentials, sign up google)
```

**Comment by FelixMalfait** [comment]
Why do we want that? As a user I usually like when routes reflect what I do. Having routes doesn't prevent us from creating smooth transitions / without loading time

**Comment by Bonapara** [comment]
@charlesBochet WDYT? 

From a product perspective:
I should be able to go "backward/forward" in the onboarding
I shouldn't notice I'm changing URLs between steps on the onboarding (There should be animations betweens steps and no glitches)

**Comment by FelixMalfait** [comment]
I think we have higher priority tasks than this one which is debatable so I'm closing it. If you disagree please re-open
