### ISSUE TITLE
I can unset an object's relationship

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#985]
Once you assign a point of contact to an opportunity, a company to a person, or an account owner to a person. It's not possible to unset it. You can re-assign to another object, but you cannot come back to the initial state where the relationship is undefined.

# Current behavior:

I can edit, but not remove a value on a single entity picker:

https://github.com/twentyhq/twenty/assets/19412894/a4f6f32f-8fed-4c61-9fe1-cd5838d021a8

# Wanted behavior:

![Image](https://github.com/twentyhq/twenty/assets/19412894/45434cda-fd65-4673-b890-1ab8ed75900a)

```[tasklist]
### Tasks
- [ ] Add the ability to have a None option in SingleEntitySelect (pass icon + label as props)
- [ ] Use it in UserPicker as optional parameter
- [ ] Update GenericEditableRelationCellEditMode to unset the relation
```

**Comment by FelixMalfait** [comment]
Are we sure this would work well? I feel like it could be a bit confusing. I've seen that for multi-select pickers but don't remember seeing this much for single-entity picker. It wouldn't be consistent with keyboard behavior too (if I press enter, that doesn't deselect, does it?)

Maybe displaying a X in the search on edit mode if something is selected?

**Comment by Bonapara** [comment]
Agree with you @FelixMalfait. A better solution would be to introduce a custom "No owner" menu item in the picker that would reset the field to its empty state:

![Image](https://github.com/twentyhq/twenty/assets/19412894/45434cda-fd65-4673-b890-1ab8ed75900a)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=7787-128569&mode=design&t=Kg8gykbQHd3TdVkc-4

**Comment by FelixMalfait** [comment]
Great! That shouldn't be too hard to implement

**Comment by Jmarin123** [comment]
If no one is working on this I could work on it!

**Comment by FelixMalfait** [comment]
Thanks a lot @Jmarin123 ! Assigning it to you

**Comment by charlesBochet** [comment]
@Jmarin123 I have added some guidance in the task list of the description
